sudo: required

services: docker

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN # DockerHubのAccessTokenセット:DockerHubの制限への対応
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test